name: Actualizar Resultados

on:
  workflow_dispatch:  # 🔹 Permite ejecutar el workflow manualmente desde GitHub Actions
  repository_dispatch:
    types: [update_resultados]  # 🔹 Permite ejecutar el workflow desde `script.js`

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales de GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Guardar datos en resultados.json
        run: |
          echo '${{ github.event.client_payload.data }}' > data/resultados.json
          cat data/resultados.json  # 🔹 Muestra el contenido del archivo en la consola
          git add data/resultados.json
          git commit -m "Actualización automática de resultados"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
