name: Actualizar Resultados

on:
  workflow_dispatch:  # 🔹 Habilita ejecución manual
  repository_dispatch:
    types: [update_resultados]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales de GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Guardar datos en resultados.json
        run: |
          echo '${{ github.event.client_payload.data }}' > data/resultados.json
          cat data/resultados.json
          git add data/resultados.json
          git commit -m "Actualización automática de resultados"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 🔹 Ahora usamos `TOKEN` en lugar de `GITHUB_TOKEN`
